version: '3.8'

networks:
  web_proxy:
    external: true

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: clay_cutter_orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - web_proxy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/clay_cutter_orders
      SECRET_KEY: your-secret-key-change-in-production
      UPLOAD_DIR: /app/uploads
    volumes:
      - ./data/uploads:/app/uploads
    networks:
      - web_proxy
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    networks:
      - web_proxy
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jonans-print-shop.rule=Host(`printshop.localhost`)"
      - "traefik.http.routers.jonans-print-shop.entrypoints=web"
      - "traefik.http.services.jonans-print-shop.loadbalancer.server.port=80"
      - "traefik.http.routers.jonans-print-shop.middlewares=printshop-headers"
      - "traefik.http.middlewares.printshop-headers.headers.customrequestheaders.X-Forwarded-Proto=http"
      - "traefik.http.middlewares.printshop-headers.headers.customrequestheaders.X-Forwarded-Port=80"

  clamav:
    image: clamav/clamav:stable
    volumes:
      - ./data/uploads:/scan
    command: ["clamd"]
    networks:
      - web_proxy
    profiles:
      - security
